# Generated by Django 5.1.1 on 2024-11-22 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_user_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='role',
            field=models.CharField(choices=[('GUEST', 'Guest'), ('PLAYER', 'Player'), ('STAFF', 'Staff'), ('ADMIN', 'Admin'), ('ACADEMY', 'Academy'), ('SUPERADMIN', 'Superadmin')], default='GUEST', max_length=255),
        ),
    ]
