# Generated by Django 5.1.1 on 2024-10-11 06:45

import booking.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('coupon_code', models.CharField(max_length=255, unique=True)),
                ('validity', models.DateTimeField(blank=True, null=True)),
                ('max_users', models.IntegerField(default=1)),
                ('max_count', models.IntegerField(default=1)),
                ('redeem_count', models.IntegerField(default=0)),
                ('exclusive_for', models.CharField(blank=True, max_length=255, null=True)),
                ('discount_type', models.CharField(choices=[('AMOUNT', 'Amount'), ('PERCENTAGE', 'Percentage')], default='AMOUNT', max_length=255)),
                ('discount_value', models.FloatField(default=0.0)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('REDEEMED', 'Redeemed'), ('EXPIRED', 'Expired')], default='ACTIVE', max_length=255)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coupon_created_by', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coupon_modified_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('locality', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=10, null=True)),
                ('state', models.CharField(blank=True, max_length=10, null=True)),
                ('contact_person', models.CharField(blank=True, max_length=10, null=True)),
                ('contact_number', models.IntegerField(blank=True, default=0, null=True)),
                ('image_1', models.ImageField(blank=True, null=True, upload_to=booking.models.location_image_one_directory_path)),
                ('image_2', models.ImageField(blank=True, null=True, upload_to=booking.models.location_image_two_directory_path)),
                ('image_3', models.ImageField(blank=True, null=True, upload_to=booking.models.location_image_three_directory_path)),
                ('image_4', models.ImageField(blank=True, null=True, upload_to=booking.models.location_image_four_directory_path)),
                ('image_5', models.ImageField(blank=True, null=True, upload_to=booking.models.location_image_five_directory_path)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='location_created_by', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='location_modified_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Pitch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pitch_number', models.IntegerField(default=1)),
                ('pitch_type', models.CharField(choices=[('NATURAL_TURF', 'Natural Turf'), ('ARTIFICIAL_TURF', 'Artificial Turf')], default='NATURAL_TURF', max_length=255)),
                ('starting_time', models.TimeField()),
                ('ending_time', models.TimeField()),
                ('break_starting_time', models.TimeField(blank=True, null=True)),
                ('break_ending_time', models.TimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=255)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pitch_created_by', to=settings.AUTH_USER_MODEL)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pitch_location', to='booking.location')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pitch_modified_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('booking_date', models.DateField()),
                ('time_slot', models.CharField(max_length=255)),
                ('total_amount', models.FloatField(default=0.0)),
                ('discount', models.FloatField(default=0.0)),
                ('net_amount', models.FloatField(default=0.0)),
                ('paid_amount', models.FloatField(default=0.0)),
                ('balance_amount', models.FloatField(default=0.0)),
                ('status', models.CharField(choices=[('BOOKED', 'Booked'), ('CANCELLED', 'Cancelled')], default='BOOKED', max_length=255)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('booking_for', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booking_by_user', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booking_created_by', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booking_modified_by', to=settings.AUTH_USER_MODEL)),
                ('applied_coupon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booking_coupon', to='booking.coupon')),
                ('pitch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booking_pitch', to='booking.pitch')),
            ],
        ),
    ]
