# Generated by Django 5.1.1 on 2024-10-11 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_alter_location_city_alter_location_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='contact_person',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
