# Generated by Django 5.1.1 on 2024-10-11 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_alter_location_contact_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeslot',
            name='slot_end_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
