# Generated by Django 5.1.1 on 2024-10-17 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_alter_coupon_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('BOOKED', 'Booked'), ('CANCELLED', 'Cancelled'), ('CONFIRMED', 'Confirmed'), ('PENDING', 'Pending'), ('RESERVED', 'Reserved')], default='BOOKED', max_length=255),
        ),
    ]
