# Generated by Django 5.1.1 on 2024-10-24 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0010_reservedbooking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservedbooking',
            name='exception_dates',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reservedbooking',
            name='weekdays',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
