# Generated by Django 5.1.1 on 2024-11-07 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0011_alter_reservedbooking_exception_dates_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='transactions',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
